### ISSUE TITLE
Advanced display settings do not persist on forms

### ISSUE THREAD

**Issue by fjarrett** [wpninjas/ninja-forms#1253] opened 2016-03-17 19:53 UTC
WordPress 4.4.2
Ninja Forms 2.9.37

Steps to reproduce:

* Edit a form
* Navigate to Advanced > Display Settings
* Turn off some switches

<img width="1111" alt="screen shot 2016-03-17 at 2 48 48 pm" src="https://cloud.githubusercontent.com/assets/522158/13859102/b8a95f66-ec4f-11e5-91c6-560b8fd8be4a.png">

* Click Done
* Click Publish
* Click All Forms
* Edit the same form
* Navigate to Advanced > Display Settings
* Settings did not persist

<img width="1112" alt="screen shot 2016-03-17 at 2 49 11 pm" src="https://cloud.githubusercontent.com/assets/522158/13859157/02b6ab86-ec50-11e5-8d0d-c7f09f1465e0.png">

**Comment by kstover** [comment] 2016-03-18 01:38
I think that this is a breakdown in toggles and how their saved (1 vs true, 0 vs false). My guess is that the proper value is saved in the database, but not being displayed. Taking a look now.

**Comment by fjarrett** [comment] 2016-03-18 01:48
@kstover Yes, I believe you are right.

**Comment by kstover** [comment] 2016-03-18 02:15
Should be fixed in master now.

**Closed** 2016-03-18 02:15 UTC

**Comment by kstover** [comment] 2016-03-18 02:27
For posterity, this was being caused by setting type defaults overriding those saved in the database. Was a JS issue.
