### ISSUE TITLE
Admin Labels in Emails

### ISSUE THREAD

**Issue by jameslaws** [wpninjas/ninja-forms#526] opened 2015-03-08 03:00 UTC
We had a user submit this for discussion so I'm placing it here so it doesn't get lost and we can discuss it's merits and possible implementations.

_"Over the past 6 months, we've moved roughly 60 forms from a very old implementation of http://www.formtools.org. The one feature that my team was very used to was the ability to create a label that shows up differently in the admin vs. the one the user sees. You guys call this "Admin Labels"._

_The one difference with NF's implementation vs. FormTools is that the email that gets kicked out to the form admin still uses the User Facing label instead of the Admin Label. Does that make sense? I was curious to talk to you guys about whether that was something you guys agreed with or if you were happy with your current implementation. The way I envision it is exactly as you have it, but emails that go to the admin have the Custom Admin labels and emails that go to the form submitter get the User Facing Labels._

_The other thing they mentioned to me that they'd like to see is the ability to add Admin Labels to pure "text" fields._

_I'm not saying this is how things "should be", I just wanted to open a discussion from a users point of view and see what you guys thought."_

**Comment by platschi** [comment] 2015-10-18 22:20
+1 !  Would be great to have the admin labels sent by email rather than the user facing labels.

Sending out admin labels (if not empty) instead of "user facing" label would make it so much easier to e.g. create multilingual versions of a question or booking form (or whatever one can think of), even if the email-receiving admin does not understand the language of the form, at least she understands the admin labels sent by email and could work with that information.

Any possibility to force-send admin labels by email this at the moment?

**Comment by markandcurry** [comment] 2016-02-25 18:29
+2! I'm trying to do this right now to no avail.

**Comment by kjohnson** [comment] 2016-09-01 01:10
Duplicate of #526.

**Closed by kjohnson** 2016-09-01 01:10 UTC
Labels: suggestions

**Comment by randyjensen** [comment] 2016-09-01 01:40
It's cool that this got closed, but how is it a duplicate of itself?

**Comment by kjohnson** [comment] 2016-09-01 01:46
My bad. Wrong number.
