### ISSUE TITLE
The sub:sequence merge tag is not populating data into the hidden field.

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#2895] opened 2017-07-20 14:13 UTC
The sub:sequence merge tag is not populating data into the hidden field.

**Comment by wpnzach** [comment] 2017-08-02 20:11
Increased priority for this issue based on customer feedback.  Does not work in most addons, including Trello

**Comment by wpnzach** [comment] 2017-08-02 20:26
duplicate of #2294

**Closed by wpnzach** 2017-08-02 20:26 UTC
Labels: ADMIN: Submissions, BUILDER: Merge Tags, DIFFICULTY: Easy, FRONT: Processing, PRIORITY: High, VALUE: Modern
