### ISSUE TITLE
Define define('DONOTCACHEPAGE', TRUE); when form exists on page.

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#928] opened 2015-09-28 02:06 UTC
Define define('DONOTCACHEPAGE', TRUE); on ALL form output.  This is the most common method to avoid caching issues.  I am tagging as high priority as I believe this will alleviate a LOT of support headaches and seems to be the most universal way to handle caching.

**Comment by jameslaws** [comment] 2015-12-07 14:09
I know we are about to do a minor release to the 2.9.x branch. I see this has labeled "high risk". Is it really? Seems like a really quick thing we could test and add to the minor release for a large impact on decreasing support.

**Comment by jameslaws** [comment] 2015-12-08 17:24
@kjohnson and @kstover: Thoughts?

**Comment by kjohnson** [comment] 2016-09-01 01:07
Duplicate of #483.

**Closed by kjohnson** 2016-09-01 01:07 UTC
Labels: bug, enhancement, high risk, wait for feedback
