### ISSUE TITLE
Calculation conversion - nested calcs bug

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#3047] opened 2017-09-08 15:47 UTC
If calculations were nested in 2.9, when converted, only the topmost calculation is properly output as a "calc" merge tag.  All other calcs deeper into the nest are marked as "field" merge tags instead.

Here is a sample form:

Repro steps (in 2.9):

1. Create a form with a calc field that outputs the value of a textbox.  
2. Create a second calc that adds the first calc with the value of another textbox.
3. Convert to 3.0

In the converted form, the calculation from step one above will be perfect, but the calc from step two will show {field:textbox} + {field:calc_1} instead of {field:textbox} + {calc:calc_1}, breaking the forms calculations.

**Comment by kjohnson** [comment] 2017-09-08 19:26
@wpnzach I wasn't able to reproduce this.

![image](https://user-images.githubusercontent.com/10858303/30228048-17866b74-94aa-11e7-8625-487eaa70d237.png)

![image](https://user-images.githubusercontent.com/10858303/30228023-f5f23402-94a9-11e7-9ace-3ab56f750e56.png)

**Comment by wpnzach** [comment] 2017-09-08 19:28
[CalcTest---09-08-2017-.txt](https://github.com/wpninjas/ninja-forms/files/1288921/CalcTest---09-08-2017-.txt)

**Comment by kjohnson** [comment] 2017-09-08 19:31
Updated Test to better match the reproduction steps.

| x2.9.x | v3.x |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/30228179-99954d88-94aa-11e7-895b-800bc71ef1fe.png) | ![image](https://user-images.githubusercontent.com/10858303/30228194-a5db261c-94aa-11e7-91d5-71257fba0fd5.png) |

**Comment by kjohnson** [comment] 2017-09-08 19:33
@wpnzach this may have already been resolved, elsewhere.

![image](https://user-images.githubusercontent.com/10858303/30228309-1e55c200-94ab-11e7-8cea-5623cc9d007e.png)

**Comment by kjohnson** [comment] 2017-09-08 19:44
The issue is not currently reproducible. Closing.

**Closed by kjohnson** 2017-09-08 19:44 UTC
Labels: PRIORITY: High, UPGRADE to THREE, VALUE: Painless
