### ISSUE TITLE
Showing a new Form is not possible anymore

### ISSUE THREAD

**Issue by dirko0816** [wpninjas/ninja-forms#3113] opened 2017-10-01 14:17 UTC
- I have 1 form showing correctly on a page with [ninja_form id=1]
on another Page a 2nd Form [ninja_form id=6] is corrupt, showing only
```
/*
CONTACT ME
/*]]>*/
```
viewing source-code of the page there is some incomplete code with unclosed CDATA-stuff
```
<div id="nf-form-6-cont" class="nf-form-cont" aria-live="polite" aria-labelledby="nf-form-title-6" aria-describedby="nf-form-errors-6" role="form">
/*<!--[CDATA[*/<span id="nf-form-title-6"class="nf-form-title"-->
<h3>Contact Me</h3>
<div class="nf-form-wrap ninja-forms-form-wrap">
<div class="nf-response-msg"></div>
<div class="nf-debug-msg"></div>
<div class="nf-before-form">
<nf-section></nf-section>
</div>
<div class="nf-form-layout">
<div class="nf-before-form-content"></div>
</div><div class="nf-after-form"></div>
</div>
/*]]&gt;*/
</div>
```

See here: http://www.buerger-griesheim.de/floh-heim/

Can you help please?
Dirk

**Comment by Much2tall** [comment] 2017-10-06 14:20
@dirko0816 

We can't reproduce this on our local systems. Could you please reach out to our support team at https://ninjaforms.com/contact/ ? They should be able to get you sorted out.

Closing this, as this repository is for confirmed bugs with the software.

**Closed by Much2tall** 2017-10-06 14:20 UTC
