### ISSUE TITLE
Form is not submitting if user is not logged in

### ISSUE THREAD

**Issue by ignaty** [wpninjas/ninja-forms#1117] opened 2016-02-16 09:10 UTC
We're started experience this issue after the update.

If user (e.g. admin) is logged in, then for work as it should, but if user is not logged in (e.g. all other regular visitors) then form stuck in "processing" status giving "Uncaught TypeError: Cannot read property 'hide_complete' of undefined" error.

I though it's related to the admin-ajax being blocked to the unregistered users, but I can see that "/wp-admin/admin-ajax.php?action=ninja_forms_ajax_submit" is giving code 200 which is fine.

Anyone experienced that problem before?

Any tips, hints or solutions will be very appreciated.

Thank you.

**Comment by jdoevans** [comment] 2016-03-14 02:18
I'm experience this issue too.  Have you have any progress on this?

**Comment by bucketpress** [comment] 2016-04-26 02:34
Having the same issue as well. Tested in Firefox - this issue does not occur. On Chrome, this error happens. Have yet to find a solution to this.

**Comment by bucketpress** [comment] 2016-04-26 04:40
Ok, the issue should be caused by a situation where a particular form's setting was not saved properly. Thus on form submission success, the `var hide_complete = form_settings.hide_complete` found in ninja-forms-display.js returns undefined.

To solve this, go to the particular form's settings in the admin, and re-save.

**Comment by bucketpress** [comment] 2016-04-26 04:46
@ignaty , it will be good if you can change this thread's title simply to **"Uncaught TypeError: Cannot read property 'hide_complete' of undefined" during form submission**, since this has nothing to do with whether a user is logged in. Will be more useful for future users who encounter this problem.

**Comment by serteckian** [comment] 2016-06-08 11:51
I am having exactly the same issue. It happens in both Chrome and Firefox. I tried re-saving the form but the error persists. I just updated to latest 2.9.47 version but same error.
Any idea?
Thanks!

**Comment by bucketpress** [comment] 2016-06-09 09:09
@serteckian , have you tried to first uncheck the option 'Hide successfully completed form' in the form's settings, then save. Then check it again, and re-save? That worked for me up until ver 2.9.45 . Both 2.9.46 and .47 created news bugs on my side that are still unsolved, thus I'm not using them yet.

**Comment by serteckian** [comment] 2016-06-09 11:43
@bucketpress , thank you very much for your response. In my case I do not hide the form after completion. But, yes, I have tried the same approach by setting and saving all settings, then I unset the settings and save again. But still doesn't work.

However, I have found a more precise error-pattern. The problem arises when I add something to my WooCommerce cart. In that case, the following cookies are generated:
- wp_woocommerce_session_xxx...xxx	
- woocommerce_items_in_cart	
- woocommerce_cart_hash	
With these cookies the forms stop working. If they are Ajax, then the undefined typeError is thrown. While if they are Ajax, the form page simply reloads without even checking the mandatory fields.

Now, if I manually remove the cookie wp_woocommerce_session_xxx...xxx, then the forms start working just fine again.

Any idea?

**Comment by EthanEtienne** [comment] 2016-06-10 12:08
I had to upgrade to Ninja Forms 3. Follow the upgrade here:
http://developer.ninjaforms.com/access-ninja-forms-three-today/

From their blog post:
Visit the ALL Forms screen within Ninja Forms and on your keyboard start typing the Konami code ( ↑↑↓↓←→←→BA )

Upgrade the forms and publish.

*Not a joke

**Comment by kstover** [comment] 2016-06-10 21:07
Thanks for submitting such detailed reproduction steps. We're pretty sure that we've fixed this in master, and it will be released in version 2.9.48 on Monday morning EST.

**Comment by serteckian** [comment] 2016-06-11 21:53
Great! The patch has fixed the issue. Thank you very much for your support!

**Closed** 2016-09-13 18:42 UTC
