### ISSUE TITLE
Metabox toggle styles

### ISSUE THREAD

**Issue by helgatheviking** [wpninjas/ninja-forms#1130] opened 2016-03-01 16:10 UTC
Saw this when testing the new AWeber against NF2.9.x, current master branch. Seems like the styling is a bit off with the "edit" text and the toggle arrow. 

![image](https://cloud.githubusercontent.com/assets/507025/13432997/f57de22c-df9d-11e5-89c4-7927c234e0cf.png)

**Comment by kstover** [comment] 2016-03-01 16:11
Hey Kathy. Current master isn't up to date. Test vs the 2.9.x branch instead.

**Comment by helgatheviking** [comment] 2016-03-01 16:18
Still see it on 2.9.x

**Comment by jameslaws** [comment] 2016-03-01 16:19
It will actually be fixed in 2.9.34 when we ship theTHRE codebase.

**Comment by kstover** [comment] 2016-03-01 16:19
May need to blast your browser cache.

**Comment by helgatheviking** [comment] 2016-03-01 16:24
Cache cleared, but still see it.

**Comment by kstover** [comment] 2016-03-01 16:27
Do you see it on the 3.0 branch?

**Comment by jameslaws** [comment] 2016-03-01 16:27
I believe the CSS fixes are in the 3.0-upgrade branch.

**Comment by helgatheviking** [comment] 2016-03-01 16:32
Still see it on 3.0 and 3.0-upgrade, even after clearing the cache.

**Comment by jameslaws** [comment] 2016-03-01 17:15
On the 3.0-upgrade branch and switched to the 2.9.x codebase, I can't reproduce this issue, but I am on Trunk.

https://db.tt/fORzoJQC

I'll look at the current stable version of WP in a bit.

**Closed** 2016-08-01 19:43 UTC
