### ISSUE TITLE
Inoperable screen options on view submissions screen

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1873] opened 2016-09-30 04:28 UTC
> The view submissions screen offers two screen options “List View” and “Excerpt View” but these do not appear to actually change the display.
## 

Reported by Mike Glendinning
Reference: https://wpninjas.desk.com/web/agent/case/23808

**Comment by tw2113** [comment] 2016-10-13 01:50
The standard "post" post type gets the same two options, and neither seem to do anything there as well, for what it's worth.

**Comment by kstover** [comment] 2017-06-08 14:37
Closed as a duplicate of https://github.com/wpninjas/ninja-forms/issues/1488

**Closed by kstover** 2017-06-08 14:37 UTC
Labels: BUG: Minor
