### ISSUE TITLE
Option to add a display titles for fields

### ISSUE THREAD

**Issue by ramiabraham** [wpninjas/ninja-forms#1869] opened 2016-09-29 19:17 UTC
I may have missed this somewhere, but is it possible to add a "display" title for a Ninja Forms field?

For example, given the field ID of `affwp_afnf_payment_email`, what the user sees when trying to add a field in a field-select action setting is:

![field name literal](https://cloud.githubusercontent.com/assets/52581/18692485/b1356f4e-7fee-11e6-8c0d-3daec3c0aee2.png "field name literal")

Ninja Forms capitalizes the first letter of the field ID, which works great for single-term fields such as `email` or `website`, but could confuse users in cases where the field is longer, such as the field noted above.

**Comment by kjohnson** [comment] 2016-09-29 23:03
Ah, yes. Need to update that to use the nicename.

Duplicate of #1668 .

**Closed by kjohnson** 2016-09-29 23:03 UTC
