### ISSUE TITLE
New session spawned on every request

### ISSUE THREAD

**Issue by ericnicolaas** [wpninjas/ninja-forms#1236] opened 2016-03-11 21:26 UTC
I'm using Ninja Forms 2.9.33. This seems to be the same issue mentioned here: https://github.com/wpninjas/ninja-forms/issues/954

In short, every single page reload is spawning a new session with a new session ID. Tested on Twentyfifteen with only these plugins running:

- MultiSite Clone Duplicator
- Ninja Forms
- WordPress Beta Tester

**Comment by ericnicolaas** [comment] 2016-04-11 02:57
Just confirming this is still an issue in the 2.9 branch with 2.9.39, but it works correctly when switching to 3.0.

**Comment by kjohnson** [comment] 2016-07-15 15:56
Duplicate of #954 .

**Closed by kjohnson** 2016-07-15 15:56 UTC
Labels: duplicate
