### ISSUE TITLE
trim fields that validate as emails

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1582] opened 2016-08-08 16:23 UTC
trim() fields that validate as emails in 3.0.  empty spaces currently cause emails to fail validation.

**Comment by kjohnson** [comment] 2016-08-08 16:30
@wpnzach JS or PHP?

**Comment by kjohnson** [comment] 2016-08-08 16:32
Could not reproduce in THREE.

**Comment by jameslaws** [comment] 2016-09-05 02:24
I also cannot reproduce this. Closing and we can reopen if it resurfaces.

**Closed by jameslaws** 2016-09-05 02:24 UTC
Labels: unconfirmed, wait for feedback
