### ISSUE TITLE
Form not loading on specific pages

### ISSUE THREAD

**Issue by olafghanizadeh** [wpninjas/ninja-forms#3254] opened 2017-12-17 17:37 UTC
I've been running ninjaforms on a client website for months. Suddenly the forms, which works on other pages is not being loaded on a specific page. 

The only error I am getting is in the Console regarding front-end.js
`TypeError: undefined is not an object (evaluating 'e.get("default").match')`

**Comment by Much2tall** [comment] 2017-12-18 15:29
@olafghanizadeh 
I'm unable to reproduce this, and I can't ask you for further information here.
Please reach out to our support team at https://ninjaforms.com/contact/

Closing this issue, as this repository is for reporting known bugs in the software.

**Closed by Much2tall** 2017-12-18 15:29 UTC

**Comment by olafghanizadeh** [comment] 2018-01-13 12:55
I did some more testing here and it seems like Ninja Forms is unable to load 2 Forms in a single page. Has this occurred before?
