### ISSUE TITLE
Country fields fail conversion from 2.9

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#1995] opened 2016-10-21 19:28 UTC
End up as unknown field type:

![image](https://cloud.githubusercontent.com/assets/7498743/19609083/0c452232-97a3-11e6-8d78-3f015512f597.png)

**Comment by kjohnson** [comment] 2017-09-01 19:33
Possible duplicate of #1866.

**Comment by kjohnson** [comment] 2017-09-01 19:42
As #1866 suggests, already resolved.

**Closed by kjohnson** 2017-09-01 19:42 UTC
Labels: BUILDER: Fields, DIFFICULTY: Involved, PRIORITY: High, UPGRADE to THREE, VALUE: Painless
