### ISSUE TITLE
Forms will not submit when users are not logged in

### ISSUE THREAD

**Issue by WorldWideWebb** [wpninjas/ninja-forms#1121] opened 2016-02-18 22:11 UTC
I opened a support ticket regarding this with both the ninja forms group and woothemes, but thought I would add it here as well (not sure if it's the same issue as issue 1027).

I have a WooCommerce site, and since one of the recent updates (either to WC or to ninja forms), forms will no longer submit if the user is not logged in to the site. When ajax submit is turned on, I get a javascript error in the console (looks like the jquery object not being found), and when ajax is turned off, the page refreshes but the submission doesn't show up.

**Comment by cbonomini** [comment] 2016-03-15 13:26
@WorldWideWebb have you found something about it? I'm having the same issue...

thank you.

**Comment by WorldWideWebb** [comment] 2016-03-15 15:16
Not yet - Ninja Forms support isn't responding to me anymore. I'll try them again and if I get a resolution, I'll post it here.

**Comment by kstover** [comment] 2016-03-15 15:19
Hey. Sorry for the lack of updating on our part; we've been working with WooCommerce to track this down, but so far we have been unsuccessful.

We have been unable to recreate this on any of our local installations. If you can reliably recreate this on a dev environment that we can test in, that would be amazingly helpful!

We don't believe that version 3.0 will have this issue, but, again, we haven't been able to create a dev environment that presents this problem.

**Comment by cbonomini** [comment] 2016-03-15 19:52
@WorldWideWebb  and @kstover I thought the situation was between woocommerce and Ninja Forms, because when Woocommerce is deactivated it works just fine.

I had a plugin enabled YITH WooCommerce Request A Quote that was causing it. It calls a action, I didn't find why, but disabling the plugin solve the issue.

`if( ! isset( $_COOKIE['woocommerce_items_in_cart'] ) ) {
	do_action( 'woocommerce_set_cart_cookies', true );
}`

I've created a new/clean Wordpress install with Woocommerce and Ninja-forms (all latest versions) and was able to recreate it by adding the following lines of code to the functions.php file:

`add_action('init', 'woo_ninja');
function woo_ninja() {
    do_action( 'woocommerce_set_cart_cookies',  true );
}`

Hope it helps you guys to find out.

Thank you.

**Comment by WorldWideWebb** [comment] 2016-03-15 22:17
I definitely don't have that plugin, but I've done some searches through my plugin code and all of the other plugins that I have, and none of them are calling that set cookies action.

**Comment by kstover** [comment] 2016-06-10 21:07
Thanks for submitting such detailed reproduction steps. We're pretty sure that we've fixed this in master, and it will be released in version 2.9.48 on Monday morning EST.

**Closed** 2016-09-13 18:42 UTC
