### ISSUE TITLE
On error, form redraws without default values

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2839] opened 2017-07-05 16:54 UTC
If a field in a form is prepopulated with a default value, when that form is submitted and an error encountered (such as a missed required field), the default value is not present in the field on the redraw.

**Comment by Much2tall** [comment] 2017-07-21 00:37
@wpnzach
I'm unable to reproduce this. Were any add-ons involved?
Multi-part maybe?

**Comment by Much2tall** [comment] 2017-07-21 15:03
Appears to be working. Closing issue unless it reappears.

**Closed by Much2tall** 2017-07-21 15:03 UTC
Labels: DIFFICULTY: Easy, VALUE: Friendly, VALUE: Painless
