### ISSUE TITLE
Something is breaking debug display

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#2157] opened 2016-12-01 21:13 UTC
Something has changed in the way we handle displaying debug error messages. Which seems to be causing PayPal and Webhooks debug mode to break. 

Closes wpninjas/ninja-forms-webhooks#21

**Comment by kstover** [comment] 2016-12-15 20:48
Closing as a duplicate of https://github.com/wpninjas/ninja-forms/issues/2207

**Closed by kstover** 2016-12-15 20:48 UTC
Labels: BUG: Urgent
