### ISSUE TITLE
`jQuery(...).find(...).mask is not a function` error.

### ISSUE THREAD

**Issue by yaquawa** [wpninjas/ninja-forms#3216] opened 2017-11-28 03:16 UTC
When use custom input mask (in my case the 'tel' field), cause error shown below.

```
Uncaught TypeError: jQuery(...).find(...).mask is not a function
    at n.onRender (front-end.js?ver=3.2.4:2)
    at Object._triggerMethod (front-end-deps.js?ver=3.2.4:20)
    at n.triggerMethod (front-end-deps.js?ver=3.2.4:20)
    at n.render (front-end-deps.js?ver=3.2.4:20)
    at constructor.show (front-end-deps.js?ver=3.2.4:20)
    at n.onRender (front-end.js?ver=3.2.4:2)
    at Object._triggerMethod (front-end-deps.js?ver=3.2.4:20)
    at n.triggerMethod (front-end-deps.js?ver=3.2.4:20)
    at n.render (front-end-deps.js?ver=3.2.4:20)
    at n.render (front-end-deps.js?ver=3.2.4:21)
```

**Comment by Much2tall** [comment] 2017-11-28 20:41
@yaquawa 
I'm not able to reproduce this.
Please get in touch with our support team at ninjaforms.com/contact.
They should be able to get your issue sorted out.

Closing this issue, as this repository is for known issues with the codebase, not support requests.

**Closed by Much2tall** 2017-11-28 20:41 UTC
