### ISSUE TITLE
Cannot use Enter/Return key to submit form

### ISSUE THREAD

**Issue by Curtisbrownlee** [wpninjas/ninja-forms#3236] opened 2017-12-07 18:26 UTC
- **What actions are you taking?**
  - What had happened was... 
User entered information into their form and pressed enter/return to attempt to submit the form.
- **What are you expecting to occur?**
  - What I was expecting to happen was...
User expected the form to process/submit by using the enter/return key instead of clicking with their mouse.
- **What is occurring instead?**
  - What *actually* happened was...
The enter/return keystroke was ignore and the page did not submit.

**Comment by TonyC5** [comment] 2017-12-08 18:31
@Curtisbrownlee The <Enter> key triggers Submit on my Ninja Forms (3.x).  Do you have a plugin or theme component (or custom scripting) that could be interfering?  I'll ask you the standard questions that I've been asked - Does this still happen if you use a clean WordPress installation with Twenty Seventeen Theme?

**Comment by Much2tall** [comment] 2017-12-14 23:28
@Curtisbrownlee 
I cannot reproduce this locally.
<Enter> key works for me, assuming that the Submit button has browser focus.

Closing this issue, as this repository is for confirmed issues with the codebase.

**Closed by Much2tall** 2017-12-14 23:28 UTC

**Comment by TonyC5** [comment] 2018-01-15 22:25
I know this is closed, but is this Issue related to #3277?
