### ISSUE TITLE
Calc merge tags are not on present in email or success message actions

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1903] opened 2016-10-03 16:13 UTC
Calc merge tags do not appear in email or success message actions. 

Replication Steps:
1. Create a new form. 
2. Add a calc variable.
3. Go to emails and actions tab.
4. Add an email action.
5. In the RTE use the merge tag selector to try to add the calc variable. You'll notice the calc merge tags are not present in the merge tag selector.

**Comment by jameslaws** [comment] 2017-01-23 15:48
Duplicate of #2041

**Closed by jameslaws** 2017-01-23 15:48 UTC
Labels: BUG: Minor
