### ISSUE TITLE
Add "view all" option when viewing Submissions or visual notification of which forms have new submissions

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2900] opened 2017-07-21 13:31 UTC
A user has reported difficulty finding which forms have new submissions when viewed under Ninja Forms>Submissions. They have a large number of forms and filtering by form to find new submissions is the pain point. Email notifications in this case are not ideal. They suggest:

1) Having a "view all" style option so that all submissions can be viewed at once

-or-

2) Having visible notifications (like a little bubble w/ number etc) indicating which forms have new submissions.

**Comment by Much2tall** [comment] 2017-07-21 13:58
2nd solution is probably more ideal.
We could put a value in the user_meta table that stores an array of sub IDs that the user hasn't viewed.
The concern is that it would need to be a system that the user opts into. Otherwise, it could create unnecessary admin notification bloat.

**Comment by kstover** [comment] 2017-09-11 14:01
Closed as a duplicate of https://github.com/wpninjas/ninja-forms/issues/3002

**Closed by kstover** 2017-09-11 14:01 UTC
Labels: ADMIN: Submissions, DIFFICULTY: Easy, Feature Request, VALUE: Friendly
