### ISSUE TITLE
Minification plugins (WP-Rocket) break Ninja Forms JS

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#2897] opened 2017-07-20 17:40 UTC
Plugins like WP-Rocket that minify all JS/CSS on a page seem to break Ninja Forms from working properly.  Can we combat this at all?  I don't know why re-minifying would break our JS since i'd assume it should just be white space removal.  

As WP-Rocket gains in popularity, these support issues are rising rapidly.  Would be awesome if we could find a way to avoid them.

**Comment by Much2tall** [comment] 2017-07-20 23:12
@wpnzach 

Javascript isn't designed to be minified twice. Moreover, when we minify it ourselves, we have control over which minification library is being used and what settings it's applying.

External minification libraries being applied by other plugins often don't care about the settings. They're just applying whatever settings will achieve the smallest data footprint.

While it is possible to combat this by writing code that complies to very strict standards, it is unlikely that we can ever completely remove it as an issue because of the nature of the beast. At the end of the day, no other plugin should be responsible for minifying a library that exists within another library. Minification of scripts should be the sole responsibility of the entity that manages the plugin.

**Comment by wpnzach** [comment] 2017-07-21 13:40
I don't disagree...but the reality is that this is becoming a big burden in support.  We're getting better at catching it earlier, but the issue is only growing as plugins like this increase in popularity.  I don't think it unwise to think through mitigation of these issues.

What about, specifically for WP Rocket, if we added the exception for our JS/CSS ourselves if we detect that its installed?

**Comment by Much2tall** [comment] 2017-07-21 13:55
I don't have a problem with discussing mitigation amongst the development team. However, I don't want to get your hopes up. Detection of other plugins running is sticky issue, and it would need to be done in PHP, as the entire problem is that the secondary minification is breaking the JS/CSS. If we put our solution into that, it'll be just as broken as the rest of the code in there.

**Comment by kjohnson** [comment] 2017-07-25 19:30
@wpnzach I think that we are going to need some additional details before we can move forward with this.

First, when you say that minification plugins "seem to break Ninja Forms from working properly", can you provide more specifics? In particular can you provide error messages, workarounds, or even a collection of tickets that we can research?

**Comment by Much2tall** [comment] 2017-07-25 20:02
Current plan is to get a copy of WP Rocket and create a process for auto-adding our plugin files to their "ignore" section. This would prevent their plugin from re-minifying our code.

The devs at WP Rocket have been receptive to this and are willing to provide us with guidance in setting up a solution.

**Comment by kjohnson** [comment] 2017-07-27 01:12
@wpnzach I heard you talking @MongolianMisfit and @jmcelhaney through a verbal update of the WP Rocket compatibility.

Can you post an update here?

**Comment by wpnzach** [comment] 2017-07-27 01:25
@kstover was looking into this and can speak to it better than I for WP Rocket specifically

**Comment by kjohnson** [comment] 2017-08-10 17:08
The recent update of WP Rocket no longer causes any issue with Ninja Forms. Closing.

**Closed by kjohnson** 2017-08-10 17:08 UTC
Labels: Waiting on Feedback

**Comment by kcg23** [comment] 2018-01-27 02:06
Yes, 

same problem here with the same code error code in the console:
constructor {name: "Error", message: "An "el" .nf-form-layout must exist in DOM", stack: "Error: An "el" .nf-form-layout must exist in DOM↵ …p-includes/js/underscore.min.js?ver=1.8.3:5:2350)"}

The problem is, I disabled WP fastest cache and all other caching plugins, it still gave me this error. 

Any ways fix this?

It is very frustrating when you have a problem like this on a production website. we have 6 different forms with multiple options and we have no other ways to make it work.

**Comment by Slapbox** [comment] 2018-06-06 01:10
A comprehensive list of JS files that should be excluded from minification would be very helpful.
