### ISSUE TITLE
Purge database entries on uninstall

### ISSUE THREAD

**Issue by str** [wpninjas/ninja-forms#811] opened 2015-07-29 18:06 UTC
I wanted to uninstall the plugin as it's confusing how it was installed and I want a clean installation, but after I activate it again, it has the same data and errors. How can I purge the database entries and tables installed by NinaForms?

**Comment by kstover** [comment] 2015-07-29 18:51
@str You can remove all settings and data by selecting the "
Remove ALL Ninja Forms data upon uninstall?" option underneath Forms->Settings->Advanced. Then, when you deactivate and delete the plugin through the WordPress plugins page, it will clear all the data.

I think that you'd be better served asking questions through our support form here: ninjaforms.com/contact/

Tickets here on GitHub are generally reserved for bug reports and enhancement ideas.

**Comment by str** [comment] 2015-07-29 19:25
OK, so, this is a bug :( I clicked on the "Remove ALL Ninja Forms data upon uninstall?" checkbox and saved the data. When the page reloaded, the checkbox was unchecked, so I thought the value was not stored.  I searched in the code and found a 'delete_on_uninstall' was only used in the wp-content/plugins/ninja-forms/uninstall.php file.  I var_dumped the settings, and found the delete_on_uninstall flag was not set.  That's a bug.

**Comment by kstover** [comment] 2015-07-29 19:26
What version of Ninja Forms are you using? I just tested and couldn't reproduce what you're seeing.

**Comment by str** [comment] 2015-07-29 19:28
### Environment ###

Home URL:                http://ballista.bulldogtutors.com
Site URL:                http://ballista.bulldogtutors.com
Ninja Forms Version:     2.9.21
WP Version:              4.2.2
WP Multisite Enabled:    No
Web Server Info:         Apache/2.4.10 (Ubuntu)
PHP Version:             5.6.7
MySQL Version:           5.6.24
PHP Locale:              decimal_point: .thousands_sep: int_curr_symbol: currency_symbol: mon_decimal_point: mon_thousands_sep: positive_sign: negative_sign:
WP Memory Limit:         40 MB
WP Debug Mode:           No
WP Language:             Default
WP Max Upload Size:      200 MB
PHP Post Max Size:       200 MB
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
SMTP:                    localhost
smtp_port:               25
Default Timezone:        Default timezone is UTC

### Plugins ###

Installed Plugins:       Akismet by Automattic version 3.0.0
                         CF Post Formats by crowdfavorite version 1.1
                         FlexSlider by Minti FlexSlider version 1.0.8
                         Ninja Forms by The WP Ninjas version 2.9.21
                         Post Types Order by Nsp Code version 1.6.8
                         Recent Tweets Widget by Theme Prince version 1.3
                         Revolution Slider by ThemePunch version 3.0.95
                         SMK Sidebar Generator by Smartik version 2.3.2
                         WordPress SEO by Joost de Valk version 1.5.3.2
                         WP-Mail-SMTP by Callum Macdonald version 0.9.5
                         WP Migrate DB Pro Media Files by Delicious Brains version 1.1.4
                         WP Migrate DB Pro by Delicious Brains version 1.4.1

**Comment by kstover** [comment] 2015-07-29 20:22
Going to close this issue in favour of the other one. #812.

**Closed by kstover** 2015-07-29 20:22 UTC
Labels: question, wontfix
