### ISSUE TITLE
In 2.9.x Calculations are not working on the front end if Stripe is enabled

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1484] opened 2016-07-06 19:14 UTC
In the 2.9.x code base, if a form has calculations with Stripe enabled the calculations are not working on the front end of the site. I'm seeing a JS console error that I've detailed in the the screen shot below. 

Screenshot:
![screen shot 2016-07-06 at 2 58 04 pm](https://cloud.githubusercontent.com/assets/9393977/16631157/b199ebc6-438b-11e6-9c14-e077b5da58b3.png)

Replication Steps(In 2.9.x codebase, with the Stripe Add-on active):
1. Create a new form.
2. Add a list field, number field, and a calculation field. 
3. Goto the settings tab 
4. Enable stripe. 
5. Preview the form and test your calculations.

**Comment by kjohnson** [comment] 2016-07-20 17:16
Could not reproduce.

**Comment by kjohnson** [comment] 2016-09-11 19:50
Resolved by v3.

**Closed by kjohnson** 2016-09-11 19:50 UTC
Labels: bug, wait for feedback
