### ISSUE TITLE
Form submissions while logged in results in JavaScript error

### ISSUE THREAD

**Issue by mattsparks** [wpninjas/ninja-forms#2580] opened 2017-03-30 14:34 UTC
When submitting a form while logged in, in this case as admin, results in the following error:

```
Notice: Error trying to reset grecaptcha
```

![screen shot 2017-03-30 at 10 26 28 am](https://cloud.githubusercontent.com/assets/1678388/24509340/1858df00-1534-11e7-8dbf-bed7e0b38244.png)

This causes the form to not submit. The form that throws this error doesn't have a recaptcha, it does however have an anti-spam field.

**Comment by kjohnson** [comment] 2017-04-04 16:54
Looks like the `try/catch` isn't enough there.

We need to add a better check.

https://github.com/wpninjas/ninja-forms/blob/master/assets/js/front-end/controllers/fieldRecaptcha.js#L23

**Comment by slip** [comment] 2017-05-02 15:27
I have the same issue. I ran a live log tail on the server's mail log and it never appears to have hit the mail service at all which leads me to believe this error is preventing the form from completing the submission. Any clues on how to avoid it?

**Comment by tlambrechtsen** [comment] 2017-05-08 09:55
I'm having the same issue here
[http://hangingrockhall.org.au/contact/](http://hangingrockhall.org.au/contact/)

Any thoughts on how to fix this? I've deactivated most unessential plugins.

**Comment by jonnymaceachern** [comment] 2017-05-10 14:56
Also having this issue.

**Comment by sterlingken** [comment] 2017-06-12 17:00
I have noticed this issue as well. I'm running 3.1.4.

**Comment by kstover** [comment] 2017-06-13 18:19
The part of the error mentioned by the OP that causes the problem isn't the google recaptcha. It is the 'fields' of undefined line.

I think we'd need more data to really troubleshoot this. If you could submit a ticket through our support form, that'll help us gather the data we need. https://ninjaforms.com/contact/

This isn't a great place to track down bugs, because we may need to get some non-public data from you.

**Comment by kstover** [comment] 2017-06-13 18:20
Closing this issue for now. If we are able to track down the bug with consistent reproduction steps, we can create a new issue or re-open this one while we work on it.

**Closed by kstover** 2017-06-13 18:19 UTC
Labels: Unconfirmed
