### ISSUE TITLE
Issue when deleting fields

### ISSUE THREAD

**Issue by anastasis92** [wpninjas/ninja-forms#3027] opened 2017-09-05 06:49 UTC
When I delete a field from the form and click the publish button an infinite loop occurs. After I refresh the browser the field is not deleted.

**Comment by Much2tall** [comment] 2017-09-05 13:36
@anastasis92 

We're unable to reproduce this locally, and as this repository is for known, existing issues, please contact our support team for further diagnosis of the problem. (https://ninjaforms.com/contact/)

Our support staff would be happy to help walk you through resolving your problem.

**Closed by Much2tall** 2017-09-05 13:36 UTC
