### ISSUE TITLE
Images are not able to be used in HelpText

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#3333] opened 2018-02-02 15:58 UTC
Images are not able to be used in HelpText
This did work in earlier versions. (Tested and confirmed functional in 3.2.7)
In version 3.2.11, there is a 404 error for the image. However, the image shows up correctly in the builder.

**Comment by jmcelhaney** [comment] 2018-02-02 15:58
https://wpninjas.kustomerapp.com/app/customers/58ad2df33b4e101100cabccf/event/5a6e60a7273bd00001920cf1

**Comment by ericwindham** [comment] 2018-02-05 18:53
When rendering on the front-end. The double quotes for the 'src' attribute aren't being escaped correctly(I believe). You can put single quotes around the 'src' attribute and the image will work on the front end, but if you open the setting for that field in the builder again and open the display settings the double quotes will replace the single quotes and the issue comes back.

**Comment by TonyC5** [comment] 2018-02-06 14:07
Duplicate of #3293?

**Closed** 2018-03-13 17:11 UTC
Labels: DIFFICULTY: Easy, PRIORITY: Low, VALUE: Friendly
