### ISSUE TITLE
Problems with text between < and >

### ISSUE THREAD

**Issue by Anguel** [wpninjas/ninja-forms#617] opened 2015-04-15 13:16 UTC
Example:

User enters the following into the text area of a form:

This takes < 5 min but > 3 min.

The following is submitted:

This takes 3 min.

Also try entering the following and outputting the text area content into the successfully submitted page (some links will be created in the output HTML!):

This is < a but > b.
This is < c.
This is > d.

This is probably because text between < and > tags is stripped for security reasons but this can cause much trouble if the user enters text and it just disappears or is interpreted incorrectly...

Anguel

**Comment by Anguel** [comment] 2015-04-21 12:50
No comment???

**Comment by kstover** [comment] 2015-04-21 13:18
Sorry for not getting back here sooner; we've been discussing the best way to handle this internally for a few days. We haven't gotten a good solution yet, but once we do, I'll post back.

**Comment by Anguel** [comment] 2015-04-21 13:49
Thanks a lot for the reply and marking it as a bug. Take your time, I have not looked at any code but I expect this to also concern security so it's important to do it right.

**Comment by klhall1987** [comment] 2015-12-08 21:38
@kstover has this been fixed or is something we will implement in 3.0?

**Comment by Anguel** [comment] 2016-01-11 09:39
Still not fixed, IMHO this bug is extremely annoying because it not only deletes valid text entered by the visitor but can also completely change the meaning of the entered text...

**Comment by Anguel** [comment] 2016-07-11 12:05
Any news here?

**Comment by Anguel** [comment] 2016-08-23 13:32
Looks like this will never be fixed. Very disappointing regarding the fact that I have reported the bug in April 2015....

**Comment by kjohnson** [comment] 2016-08-23 13:41
@Anguel this has been resolved in Ninja Forms THREE.

<img width="491" alt="screenshot 2016-08-23 09 38 30" src="https://cloud.githubusercontent.com/assets/10858303/17893974/a2971b62-6915-11e6-97de-31cf4a19fb6a.png">

**Comment by Anguel** [comment] 2016-08-23 13:59
Many thanks for the feedback. I am looking forward to the upgrade :-)

**Comment by kjohnson** [comment] 2017-08-18 16:36
> This issue has been reported as solved, but I still experience the problem in v.3.1.9
Reported by @Anguel #2997 .

**Comment by kjohnson** [comment] 2017-08-18 16:38
@Anguel can you submit an official support request?
https://ninjaforms.com/contact

I'm not able to reproduce this locally.

However, if you reference this issue, #617, in your support request then our team can investigate the issue on your site specifically.

**Closed by kjohnson** 2017-08-18 16:38 UTC
