### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fields' of undefined

### ISSUE THREAD

**Issue by binarykitchen** [wpninjas/ninja-forms#2980] opened 2017-08-11 01:12 UTC
To reproduce, just go to https://www.deafsports.nz/contact-us/ and submit the form there.

It won't go to the confirmation page and this error gets printed in the console:

<img width="1376" alt="screen shot 2017-08-11 at 13 12 16" src="https://user-images.githubusercontent.com/177641/29198298-bd474a94-7e96-11e7-8714-8a4b02e9d02e.png">

**Comment by Much2tall** [comment] 2017-08-11 13:23
Looks like admin-ajax is failing to return valid data, and it's freaking out.

Should probably have a try/catch block for that.

**Comment by binarykitchen** [comment] 2017-08-29 01:05
guys, my customer has reported this bug again and you can reproduce it very easily yourself here:
https://www.deafsports.nz/contact-us/

can we get this fixed soon pretty please?

and here some background information:
1. initial submit request is made from that code line within the videomail extension
```js
  onSubmitted: function (videomail) {
    var formModel = nfRadio.channel('app').request('get:form', this.getFormId())

    // todo isnt 'form-' + formModel.get('id') the same as the formID already?
    nfRadio.channel('form-' + formModel.get('id')).request('add:extra', 'videomail', videomail)

    // restart submission again, this time to the real wp site
    nfRadio.channel('form-' + this.getFormId()).request('submit', formModel)
  },
```
2. which fires submit() in submit.js
3. and then this jQuery's error callback is triggered:
```js
			    error: function( jqXHR, textStatus, errorThrown ) {
			        // Handle errors here
			        console.log('ERRORS: ' + errorThrown);
					console.log( jqXHR );

					try {
						var response = jQuery.parseJSON( jqXHR.responseText );
						nfRadio.channel( 'forms' ).trigger( 'submit:response', response, textStatus, jqXHR, formModel.get( 'id' ) );
						nfRadio.channel( 'form-' + formModel.get( 'id' ) ).trigger( 'submit:response', response, textStatus, jqXHR );
					} catch( e ) {
						console.log( 'Parse Error' );
					}

			        // STOP LOADING SPINNER
					nfRadio.channel( 'forms' ).trigger( 'submit:response', 'error', textStatus, jqXHR, errorThrown );
			    }
```
`errorThrown` is empty, only outputs `ERRORS: `
`jqXHR` is a json like this `{readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …`
plus `Parse Error` is also shown.

but i can see the real error in the network console which isn't passed onto jquery:
```
XMLHttpRequest cannot load https://deafsports.nz/wp-admin/admin-ajax.php. The 'Access-Control-Allow-Origin' header contains multiple values 'https://www.deafsports.nz, *', but only one is allowed. Origin 'https://www.deafsports.nz' is therefore not allowed access.
```

will report this to the customer to fix this. nevertheless your code, your error callback, should be more robust here and have jquery try to catch the real error, the real cause before passing this further onto
```js
nfRadio.channel( 'forms' ).trigger( 'submit:response', 'error', textStatus, jqXHR, errorThrown );
```

also `submitErrors()` should be more robust and should not  process `response.errors.fields` when errors is undefined.

**Comment by binarykitchen** [comment] 2017-08-29 01:05
cc @Much2tall

**Comment by kstover** [comment] 2017-08-30 16:19
@binarykitchen While it's absolutely true that we need better error handling in that instance, we do accept pull requests, and it's well within your power to fix those issues. We are a very small team and only have time to focus on so many issues.

You said: 

> nevertheless **your code**, **your error callback**, should be more robust here and have jquery try to catch the real error, the real cause before passing this further onto...

It's not helpful to push a "your code" narrative when the success of Ninja Forms directly affects you as well. I'm sure that you don't mean it this way, but your tone comes off as arrogant, snobby, and elitist and is very demotivating.

We've added submission error handling to our stabilisation project to take a look at as soon as we are able.

**Comment by binarykitchen** [comment] 2017-08-30 22:54
sorry @kstover about my tone - probably i had a bad day myself and indeed i didn't mean it that way. i know you have lots of issues to process and are a small team. respect for that!

thanks so much for your attention and for adding this to the stabilisation project.

**Comment by nbeers22** [comment] 2017-11-03 17:09
@kstover I am getting this same issue. Considering I paid something like $180 for Ninja Forms, I would expect that your small team would either push out a product that works or fix errors when they come up over two months ago. I wouldn't expect that I need to put in a pull request. Why would I pay for a product that I have to help contribute to myself just to make it work?

**Comment by dangub** [comment] 2017-11-23 00:37
+1 on this problem. 
This doesn't work for me under basic configuration. At first it didn't work only in "admin" mode, but now also doesn't work on some of the pages. 

Do you have an ETA on resolution?

Thanks!

**Comment by nbeers22** [comment] 2017-11-23 00:42
Why would I pay something like 180 bucks for some code that I need to contribute to and send you a pull request? We pay so you can hire developers that write quality code and fix errors when they arise. Make it open-source and free and then it's a different story.

**Comment by encryptdesigns** [comment] 2017-12-20 18:12
Is there still not a patch for this? Some info on how to fix the problem would be very helpful.

**Comment by himyata** [comment] 2018-01-03 06:55
I had same problem. I created a copy of actual form and deleted old form, it resolved for me.
Don't forget to change references of old form at your pages and posts.

**Comment by madsaxe** [comment] 2018-01-12 19:40
I'm also experiencing the same issue after migrating my site from localhost to our staging server.  Tried duplicating the form as himyata suggested with no luck.  Tried creating completely new forms on the staging server.  No dice.  Has anyone found a solution for this?

**Comment by Orrefors** [comment] 2018-01-19 13:37
I'm also experience this problem. Is there coming a patch any time soon? Any one have a workaround?

**Comment by madsaxe** [comment] 2018-01-19 15:56
@Orrefors I actually figured out that the problem only triggered when I was logged in as an administrator on the site.  Have you tried using your forms while not being logged into wp-admin?

**Comment by nbeers22** [comment] 2018-01-19 16:18
It also seems to happen if you are developing on localhost

**Comment by Orrefors** [comment] 2018-01-26 11:02
If you have this problem, it might be that you removed a field from the form and you have an action that now have a type that maps to nothing. For example register user, you remove username from the form. In the action list go and edit "Register User" and map "Username" to "Email" for example. I dont know if this caused my first error. But this might solve this for some of you.

**Comment by wpnzach** [comment] 2018-02-02 17:39
I am closing this issue.  The "Cannot read property fields of undefined" is an error that shows up under many, many different conditions, mostly caused by another plugin breaking the JS the form needs to render.  As an example, the original issue is caused by an access control header issue, which is entirely outside of our control and is caused by misconfiguration of the host env.

**Closed by wpnzach** 2018-02-02 17:39 UTC
Labels: DIFFICULTY: Easy, PRIORITY: High, VALUE: Painless

**Comment by zzap** [comment] 2018-09-06 11:37
My issue was fixed with turning off [WP SES](https://wordpress.org/plugins/wp-ses/) plugin.
