### ISSUE TITLE
Form container group

### ISSUE THREAD

**Issue by paaljoachim** [wpninjas/ninja-forms#675] opened 2015-05-02 14:05 UTC
In regards to field groups.
Having a form container group that holds all the fields would give a option for the user to set certain CSS options for shaping the form container directly inside the edit form area. For instance form width, border - thickness, color and style, border radius, shadow etc.

Container group holding all the form fields.

![form-container-group-ninja-forms](https://cloud.githubusercontent.com/assets/5323259/7441326/73f96a4a-f0e3-11e4-9c30-cb3d3158a5d4.jpg)

The container would just be a standard group field where options could change depending on how the group field is used. 
If it is used as a container surrounding the form. 
Or if it is used as a group inside the form for grouping specific fields that will all be affected by the options selected in the group field. 

A group field could on the right side have a +/- or something similar as in closing or opening the group like an accordion. With long forms closing a group in the admin would be useful and could perhaps also be taken one step further by including a list type of option as the first field in the group (checkbox, radio buttons, drop down list) that includes the option to show-hide on the frontend the rest of the group. There could also be a duplicate group option to the times one needs to repeat a group more then once.

Options for a group field surrounding specific fields could be various css options similar to the container group, and likely other options as well which I have not thought of yet.

There are a lot of possibilities here that I look forward to continuing to brain storm around.
I will likely come back to this thread and add some additional screenshots and thoughts.

**Comment by kjohnson** [comment] 2016-09-01 01:28
Duplicate of #40.

**Closed by kjohnson** 2016-09-01 01:28 UTC
Labels: suggestions
