### ISSUE TITLE
Hardcoded database prefix

### ISSUE THREAD

**Issue by code-flow** [wpninjas/ninja-forms#2128] opened 2016-11-21 14:02 UTC
Hey there,
first of all thanks for the great plugin. We're currently using version 3.0.15 of it.

I've found an issue while using form submission limitation functionality. This functionality does not work due to a hardcoded database-prefix in the file [includes/Display/Render.php on line 87](https://github.com/wpninjas/ninja-forms/blob/master/includes/Display/Render.php#L87)

Maybe you can replace the whole loop with just one database query:
```
$sql = $wpdb->prepare(
		"SELECT COUNT( * ) FROM {$wpdb->prefix}posts as p INNER JOIN {$wpdb->prefix}postmeta as pm ON ( p.ID = pm.post_id ) WHERE ( ( pm.meta_key = '_form_id' AND pm.meta_value = '%d' ) ) AND p.post_type = 'nf_sub' AND ((p.post_status = 'publish')) GROUP BY p.ID",
		$form_id
	);
$count = absint( $wpdb->get_var( $sql ) );
```

Many greetings!

**Comment by kjohnson** [comment] 2016-11-21 20:16
@code-flow this is a duplicate of #1894, which will be resolved with the v3.0.16 release.

**Closed by kjohnson** 2016-11-21 20:16 UTC
