### ISSUE TITLE
Broken Placeholders

### ISSUE THREAD

**Issue by kjohnson** [wpninjas/ninja-forms#1601] opened 2016-08-11 20:13 UTC
When `init_all_the_ninja_things()` was removed from a `jQuery.ready()` call the Mask JS started to trigger before the form was ready. This can cause the placeholder values to appear as text inside of the field.
## 

Ref: https://wpninjas.desk.com/web/agent/case/20645

**Comment by klhall1987** [comment] 2016-12-28 03:36
Reported again by [Ilana](https://wpninjas.kustomerapp.com/app/customers/5862fdb5d6b18d11008a72d0/event/5862fdb6ac42cf10007a4171)

**Comment by kstover** [comment] 2017-03-17 15:50
Closing for now; can't reproduce with the current version.

**Closed by kstover** 2017-03-17 15:50 UTC
Labels: BUG: Major
