### ISSUE TITLE
Form not loading due to error with Anti Spam Question Field Key

### ISSUE THREAD

**Issue by Chris1777** [wpninjas/ninja-forms#3164] opened 2017-10-24 14:23 UTC
**The issue:**
Suddenly found that Ninja Forms wasn't being loaded on my website and it seemed that there was a problem with the JavaScript on the site. However I experienced no other problems with JavaScript and everything else worked fine. I got the following error in the console log:

> Uncaught TypeError: Cannot read property 'match' of undefined
>     at n.<anonymous> (fieldHTML.js:18)
>     at _ (backbone.min.js?ver=1.2.3:1)
>     at m (backbone.min.js?ver=1.2.3:1)
>     at f (backbone.min.js?ver=1.2.3:1)
>     at u.Channel.u.trigger (backbone.min.js?ver=1.2.3:1)
>     at n.initialize (formModel.js:62)
>     at n.e.Model (backbone.min.js?ver=1.2.3:1)
>     at new n (backbone.min.js?ver=1.2.3:1)
>     at n._prepareModel (backbone.min.js?ver=1.2.3:1)
>     at n.set (backbone.min.js?ver=1.2.3:1) 

However this error is probably due to the form not being loaded in the first place. I did several hours of troubleshooting and after doing practically everything i possibly could think of, I found that simply changing the field key of my Anti Spam Question from "spam_1" to "spam_11" solved the problem and loaded the form. I have absolutely no idea why. Beneath you can see a list of the things i did to try and solve the problem.

- **What actions are you taking?**
  - Tried to delete entire database and upload old version
     _- Didn't solve the issue_
  - Tried to manually delete tables regarding Ninja Forms
     _- Didn't solve the issue_
  - Tried to install old version of the plugin (backup) 
     _- Didn't solve the issue_
  - Tried to install fresh version and import old form
     _- Didn't solve the issue_
    _**- However the plugin did work intentionally with a fresh installment, but I had to reinstall my old form as it had a lot of dependencies in terms of other code and styling**_ 
  - Tried to disable all other plugins than Ninja Forms
     _- Didn't solve the issue_
  - Tried to change theme
     _- Didn't solve the issue_
  - Reinstalled the plugin from a backup and the database as well from a backup, went into the formbuilder and manually tried to delete fields one by one - luckily i started with the Anti Spam field, and found that this solved the issue. Afterwards i reinstalled the backup and changed the field key of this field from "spam_1" to "spam_11" - this also solved the issue.
    _- This solved the issue_

Note:
I don't know when the issue arose, sadly. I have a backup from the 2nd of October 2017 and the issue is also present here. Sadly the previous backup before this is almost a year old.

**Comment by Much2tall** [comment] 2017-10-27 15:08
@Chris1777 
In order to get this issue resolved, you'll need to reach out to our support team (ninjaforms.com/contact).
I can't reproduce this issue locally, which means it will require deeper troubleshooting by our team.

Closing issue, as this repository is for known and reproducible bugs in the code.

**Closed by Much2tall** 2017-10-27 15:08 UTC
