### ISSUE TITLE
PHP Notice:  Use of undefined constant insert_field_meta_chunk

### ISSUE THREAD

**Issue by polevaultweb** [wpninjas/ninja-forms#2661] opened 2017-04-26 09:16 UTC
```
[26-Apr-2017 09:10:12] PHP Notice:  Use of undefined constant insert_field_meta_chunk - assumed 'insert_field_meta_chunk' in /Applications/MAMP/htdocs/ninjaforms/wp-content/plugins/ninja-forms/includes/Database/FieldsController.php on line 186
```

**Comment by kstover** [comment] 2017-04-26 11:27
Duplicate of: #2653.

**Closed by kstover** 2017-04-26 11:27 UTC
