### ISSUE TITLE
Hidden Fields do not have calculations displayed under merge tag menu

### ISSUE THREAD

**Issue by Quay3** [wpninjas/ninja-forms#2078] opened 2016-11-09 15:51 UTC
Steps to reproduce:
1. Create form with hidden field and some other fields.
2. Create new calculation.
3. Open field settings window for the hidden field and in the Insert Merge Tag menu - no Calculations are listed. When you type calculation merge tag manually as default value, calculation merge tag works as expected.

**Comment by wpnzach** [comment] 2016-11-09 15:54
duplicate of #2079

**Closed by wpnzach** 2016-11-09 15:54 UTC
Labels: BUG: Minor
