### ISSUE TITLE
Unable to set a Product price as $1000 or more

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1922] opened 2016-10-06 14:13 UTC
When I try to set a Product price as $1,000 or more, it displays as $1 on the front-end.
There is an error message: Notice: A non well formed numeric value encountered in /plugins/ninja-forms/includes/Display/Render.php on line 339

### Environment ###
Home URL:                http://localhost/wordpress3
Site URL:                http://localhost/wordpress3
Ninja Forms Version:     3.0.6
WP Version:              4.6.1
WP Multisite Enabled:    No
Web Server Info:         Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/7.0.8 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version:             7.0.8
MySQL Version:           5.5.42
PHP Locale:              negative_sign:
WP Memory Limit:         40
WP Debug Mode:           Yes
WP Language:             Default
WP Max Upload Size:      32 MB
PHP Post Max Size:       32
Max Input Nesting Level: 64
PHP Time Limit:          30
PHP Max Input Vars:      1000
SUHOSIN Installed:       No
Server IP Address:       ::1
Host Name:               localhost
SMTP:                    localhost
smtp_port:               25
Default Timezone:        America/New_York

### Plugins ###
Installed Plugins:
Ninja Forms by The WP Ninjas version 3.0.6

**Comment by kstover** [comment] 2016-10-06 14:20
Duplicate of #1904.

**Closed by kstover** 2016-10-06 14:20 UTC
Labels: bug
