### ISSUE TITLE
Calculation on Multi-Step Form -> not working on last step

### ISSUE THREAD

**Issue by Czelly** [wpninjas/ninja-forms#3188] opened 2017-11-06 23:20 UTC
Dear Community!

I created a multi-part form with about 6 steps.
On my first step users have to fill in their height and weight. On the last step I want to show them their body mass index with a calculation of the two fields from step one. The calculation is not displaying, instead the code {calc:bmi} is visible.

If I print out the calculation on step one (in a html field), it is showing. On the last step only the calculation code is visible. Any idea why? Is that a known bug? Any workaround?

Would be great if someone can give me an answer.

Thanks,
Chris

**Comment by Much2tall** [comment] 2017-11-21 18:19
@Czelly 
We're not able to reproduce this on our local installations.

In order to get the swiftest answer, please reach out to our support team at (ninjaforms.com/contact).

Closing issue as this repository is for confirmed bugs in the software.

**Closed by Much2tall** 2017-11-21 18:19 UTC
