### ISSUE TITLE
Calculations & Conditionals Not Working After Loading Saved Progress

### ISSUE THREAD

**Issue by ken-prayogo** [wpninjas/ninja-forms#3122] opened 2017-10-04 02:55 UTC
- Create a Form with a "Save" button and some basic Calculations referencing different fields. Also add in an HTML field with the calculation referenced to see changes.
- Go to the form, input values to change calculations (might not be necessary to replicate error)
- Hit Save
- Reload the page, and after the form loads with saved field data, any calculations no longer work.

**Comment by ken-prayogo** [comment] 2017-10-04 02:57
Adding to the issue: Conditionals will no longer work either (after loading Save Progress)

**Comment by Much2tall** [comment] 2017-10-06 22:36
@ken-prayogo 
We're unable to reproduce the issue with conditional logic. Please ensure that you're using the latest version of all our plugins.
The calculations bug, we were already aware of.

Closing in favor of issue on save progress repo (private).

**Closed by Much2tall** 2017-10-06 22:36 UTC
