### ISSUE TITLE
Custom Input Mask option not showing when language is set to Spanish. 

### ISSUE THREAD

**Issue by devinbalram** [wpninjas/ninja-forms#1917] opened 2016-10-05 18:28 UTC
https://wpninjas.desk.com/web/agent/case/23752

Dashboard -> Settings -> Language -> Change to español -> Go to forms -> Add a single line text field -> Restrictions -> Input mask -> Set to custom -> The custom mask field does not appear.  

https://goo.gl/0DLtju

**Comment by jameslaws** [comment] 2016-10-05 18:38
Closed as a duplicate of https://github.com/wpninjas/ninja-forms/issues/1880

**Closed by jameslaws** 2016-10-05 18:38 UTC
