### ISSUE TITLE
Robust licensing/license refresh

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#673] opened 2015-04-30 18:22 UTC
Many users have valid, activated licenses but are not receiving update notices.  This is not something we've been able to replicate locally, but in most circumstances this has been resolved by deactivating and reactivating licenses.  Can we find a way to force this license refresh in a non intrusive way, such as on the WordPress "check for updates" page, or even the licenses tab itself? (check for updates would be more intuitive for most users)

@pippinsplugins, do you have any idea what might cause something like this?  I'd say approximately 10% of our support volume is directly attributable to outdated extensions even though their sites are licensed.

**Comment by pippinsplugins** [comment] 2015-04-30 18:48
The first thing I'd recommend is updating the licensing system to show feedback to the user on whether their license is activated properly.

I've done this across my plugins recently. Customers now get asked to activate their license key after installing the plugin. They also get shown an error message if the license doesn't activate properly (error is returned by the API).

I've also set my plugins up to run a daily cron job to call the `check_license` action. That way if a license ever becomes invalid, the customer gets alerted to that the next time they log into their site.

**Comment by wpnzach** [comment] 2015-04-30 18:55
Kevin and I looked into this in detail to pass on to you.

The process goes like this, with data from the current user we are testing with:

1. No updates are showing in the dashboard even though they are available on NinjaForms.com
2. Using adminer, we check the option and see that in the DB the license is marked as "valid"
3. Check NinjaForms.com and see the activation for the license on January 29th and that is had not been deactivated
4. In Ninja Forms, deactivate the license and immediately reactivate.
5. Almost immediately the update for that extension will show in the WordPress updater even though as far as we can tell, nothing in the ninja_forms options for that license in the DB changed.
6. Ninjaforms.com shows a successful deactivation and reactivation for today in the license logs.

This process needs repeated for each extension the user has.  In this instance, most of the licenses are part of a user bundle if that matters.

**Comment by pippinsplugins** [comment] 2015-04-30 20:19
One step you missed: compare the site URL the plugin is used on to the site url in the "Manage Sites" section in the store.

Do they match up? I see this quite a bit where someone will setup a staging site, activate the license, then copy the database over to the live site (or update the site URL). This results in the "valid" option still being there but the site URL not actually being activated.

If this is what's happening, the issue is resolved by having the `check_license` request fired once a day.

**Comment by wpnzach** [comment] 2015-04-30 20:46
Kevin checked that about an hour ago and I forgot to update.  The URL is the same in these instances.

**Comment by kstover** [comment] 2015-05-01 12:18
So, does the `check_license` method re-activate with our site?

**Comment by pippinsplugins** [comment] 2015-05-12 03:23
No, `check_license` only looks to see if the license / URL is active.

**Closed** 2016-09-13 15:50 UTC
Labels: bug, enhancement
