### ISSUE TITLE
 Remove ALL Ninja Forms data upon uninstall does not work in 3.0

### ISSUE THREAD

**Issue by jmcelhaney** [wpninjas/ninja-forms#1793] opened 2016-09-14 17:51 UTC
Reproduction steps.
In the 3.0 Code base, check the option to "Remove ALL Ninja Forms data upon uninstall"
Then disable and delete the Ninja Forms plugin
Reinstall the plugin and the forms will still be there.

### Environment ###
Ninja Forms Version:     3.0.5
WP Version:              4.6.1

### Plugins ###
Installed Plugins:       Ninja Forms by The WP Ninjas version 3.0.5

**Comment by kstover** [comment] 2016-09-14 18:17
Duplicate of #1265.

**Closed by kstover** 2016-09-14 18:17 UTC
Labels: bug
