### ISSUE TITLE
Limit the amount of fields that are shown on the submissions page. 

### ISSUE THREAD

**Issue by klhall1987** [wpninjas/ninja-forms#1899] opened 2016-10-03 14:15 UTC
We need to limit the amount of submissions displayed on the submissions page. If a user has a long form it becomes unreadable see the screenshot below. 

Screenshot: 
<img width="1093" alt="screen shot 2016-10-03 at 10 12 05 am" src="https://cloud.githubusercontent.com/assets/9393977/19040481/389d7f32-8952-11e6-88a5-816eda0b53bd.png">

**Comment by helgatheviking** [comment] 2016-10-05 19:49
I thought you could control this with screen options? Is that no longer the case?

**Comment by wpnzach** [comment] 2017-04-25 15:18
Upgraded to urgent as this is a blocker to finish the 3.0 release to the rest of 2.9 users.  @helgatheviking the issue is that out of the box, all of the options are checked after conversion.

**Comment by helgatheviking** [comment] 2017-04-25 15:32
You had me nervous that this was a bug with one of my plugins! I do agree that they should not all be checked by default. Good luck!

**Comment by jameslaws** [comment] 2017-06-01 02:13
Issues in this repo have become unwieldy and in many cases unreliable at identifying actual problems. In a first step to start to remdy this we are doing a clean up of older issues. 

This is issue is being closed, but if you can confirm this as an actual current bug in the 3.x codebase and the new UI, please re-open or comment and we will review it.

**Comment by wpnzach** [comment] 2017-06-01 02:18
This is still an issue after conversion, verified when we moved ninjaforms.com over

**Comment by jameslaws** [comment] 2017-06-01 02:24
Can they not be set under the screen options?

**Comment by wpnzach** [comment] 2017-06-01 02:26
The issue is that ALL of them are checked by default after conversion and
it creates support requests from users who don't know how to do that.

**Comment by jameslaws** [comment] 2017-06-01 02:30
Sure, but it's an easy change in the admin and knowing that submission are soon not going to be handled in the wp list table, I don't see this getting fixed before then.

**Comment by wpnzach** [comment] 2017-06-01 02:33
If we are willing to commit to fixing submissions before we roll this out to the rest of the 2.9 users, then we can close it.  But we can't run any conversions from 2.9 before this is fixed or the submissions are totally reworked....it's a big blocker otherwise because support will blow up.

**Comment by klhall1987** [comment] 2017-07-07 13:12
I know where to add the code and how to fix it, I need to talk with Kyle about how to get the form id in the conversion process.

**Closed** 2017-07-28 12:39 UTC
Labels: DIFFICULTY: Involved, PRIORITY: High, UPGRADE to THREE, VALUE: Painless
