### ISSUE TITLE
Additional Shortcodes for Emails/actions

### ISSUE THREAD

**Issue by wpnzach** [wpninjas/ninja-forms#574] opened 2015-03-26 17:11 UTC
The following shortcodes were requested by users:

An insert_all_fields shortcode that uses admin labels instead of field labels

Individual field shortcodes that include labels instead of just values

**Comment by kjohnson** [comment] 2016-09-01 01:22
Duplicate of #337.

**Closed by kjohnson** 2016-09-01 01:22 UTC
Labels: duplicate, suggestions
